### ISSUE TITLE
[Suggestion] Hearts Trait Tweak?

### ISSUE THREAD

**Issue by SonicX8000** [queengooborg/PlusTiC-Reforged#2]
As I mentioned on the curseforge comment...

By any chance can the Hearts Trait can be a bit balanced to where you need like 80% to 100% Health to deal +0% to +50% extra damage? In the original & forked versions the damage can get up to a 70% boost and it was between 0% to 100% Health. If you had 50% Health, it would be about a 35% boost to damage.

In the case of balancing the trait, 90% health would be 25% extra damage and below 80% would be +0% Extra Damage. 100% would provide a +50% Boost.

P.S.

Is Construct's Armory support actually being removed in the original version? Or is that for the later versions?

**Comment by queengooborg** [comment]
Made the appropriate adjustments in b069f81f41a93d35ad04ccb28732f0df699cd69e!

Regarding Construct's Armory, I don't intend to drop support in the original version of the mod, no worries there!  On the CurseForge page, you'll notice it says that the support "will be removed in Reforged" -- Reforged is the name for the new, rewritten version of the mod!

**Comment by SonicX8000** [comment]
Sorry for the delay reply, does this let the bonus damage only apply between 80% to 100% Health?

**Comment by queengooborg** [comment]
The boost is still around if you have less health, it is significantly reduced, and with a small amount of health, it's so small it's unnoticeable.  100% health will still give a 70% boost, but now 75% health gives a 30% boost, 50% health gives an 8.75% boost, and 25% health gives a 1% boost!

Below is a graph showing the boost from health at different values, comparing the old and new graphs:

<img width="1918" alt="Screenshot 2024-09-20 at 02 24 43" src="https://github.com/user-attachments/assets/c3366024-454f-4773-a269-188db1451343">
