### ISSUE TITLE
old plustic crash with ignoble

### ISSUE THREAD

**Issue by Sulferix** [queengooborg/PlusTiC-Reforged#3]
simple, game can freeze when using a tool with ignoble on it. 
[crash-2024-08-23_23.43.07-server.txt](https://github.com/user-attachments/files/16735278/crash-2024-08-23_23.43.07-server.txt)
[crash-2024-08-23_12.28.58-server.txt](https://github.com/user-attachments/files/16735283/crash-2024-08-23_12.28.58-server.txt)
first crash is with this forked version of plustic, second crash is the old 8.0.3 og version.

**Comment by queengooborg** [comment]
I wasn't able to replicate the issue, though I've not used this trait before so I wouldn't be surprised if I'm using it wrong!  I tried in both singleplayer and multiplayer (with just myself logged on; but I see in your crash log you were the only player online as well) and wasn't able to get my game to crash.

I _did_ take a look at the code and noticed some bizarre things, so I'm hoping that 449648fe7a7861245f2d9f411662b0c7f7234159 fixes the issue.

Can you give the [following custom version a try](https://github.com/user-attachments/files/16736007/plustic-ed99326-original-mc1.12.2.jar.zip) and see if the issue persists?

**Comment by Sulferix** [comment]
upon testing with that new version for a while, it seemed to have no issues. looks like you fixed it! nice response time, appreciate it.

**Comment by queengooborg** [comment]
Awesome, I'm happy to hear that it's all working and it was easily fixable!
